export const banks = [
    { label: "Access Bank", value: "Access Bank", code: "044" },
    { label: "Citibank", value: "Citibank", code: "023" },
    { label: "Ecobank Nigeria", value: "Ecobank Nigeria", code: "050" },
    { label: "Fidelity Bank", value: "Fidelity Bank", code: "070" },
    { label: "First Bank of Nigeria", value: "First Bank of Nigeria", code: "011" },
    { label: "First City Monument Bank (FCMB)", value: "FCMB", code: "214" },
    { label: "Globus Bank", value: "Globus Bank", code: "00103" },
    { label: "Guaranty Trust Bank (GTBank)", value: "GTBank", code: "058" },
    { label: "Heritage Bank", value: "Heritage Bank", code: "030" },
    { label: "Keystone Bank", value: "Keystone Bank", code: "082" },
    { label: "Opay", value: "Opay", code: "110001" },
    { label: "Palmpay", value: "Palmpay", code: "999991" },
    { label: "Parallex Bank", value: "Parallex Bank", code: "104" },
    { label: "Polaris Bank", value: "Polaris Bank", code: "076" },
    { label: "Providus Bank", value: "Providus Bank", code: "101" },
    { label: "Stanbic IBTC Bank", value: "Stanbic IBTC", code: "221" },
    { label: "Standard Chartered Bank", value: "Standard Chartered", code: "068" },
    { label: "Sterling Bank", value: "Sterling Bank", code: "232" },
    { label: "SunTrust Bank", value: "SunTrust Bank", code: "100" },
    { label: "Titan Trust Bank", value: "Titan Trust Bank", code: "102" },
    { label: "Union Bank of Nigeria", value: "Union Bank", code: "032" },
    { label: "United Bank for Africa (UBA)", value: "UBA", code: "033" },
    { label: "Unity Bank", value: "Unity Bank", code: "215" },
    { label: "VFD Microfinance Bank", value: "VFD MFB", code: "566" },
    { label: "Wema Bank", value: "Wema Bank", code: "035" },
    { label: "Zenith Bank", value: "Zenith Bank", code: "057" }
]
